Add clean option to checkout step and update file path in debug step

diff --git a/.github/workflows/02-infrastructure.yaml b/.github/workflows/02-infrastructure.yaml
--- a/.github/workflows/02-infrastructure.yaml
+++ b/.github/workflows/02-infrastructure.yaml
@@ -52,11 +52,13 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v6
+        with:
+          clean: true
       - name: DEBUG - PROVE FILE CONTENT
         run: |
           echo "============================================"
           echo "CHECKING FILE ON DISK:"
-          cat 02-infrastructure/talos-controlplane.tf | grep -C 5 "kubePrism" || echo "❌ KUBEPRISM CONFIG IS MISSING ON RUNNER DISK"
+          cat talos-controlplane.tf | grep -C 5 "kubePrism" || echo "❌ KUBEPRISM CONFIG IS MISSING ON RUNNER DISK"
           echo "============================================"
 
       - name: Setup Node.js
